### ISSUE TITLE
[REQUEST] AdAway & NekoBox

### ISSUE THREAD

**Issue by kasefuchs** [abUwUser/beyond-software-list#7]
**What entries do you suggest?**
[AdAway](https://adaway.org) - Android - Open source ad blocker using the hosts file.
[NekoBox](https://github.com/MatsuriDayo/NekoBoxForAndroid) - Android - Universal proxy toolchain for Android.

**Where they should be placed**
AdAway - Privacy and Security > Ad blockers
NekoBox - Privacy and Security > VPN

**Comment by resucutie** [comment]
Sorry for only replying now, apparently I didn't check GitHub for quite some time

Could you provide a more general explanation of NekoBox? I wanted to understand what does that application do but never got what it did

**Comment by kasefuchs** [comment]
Its a VPN client that supports many VPN/proxy protocols such as VMESS, Trojan, WireGuard, Shadowsocks, even SSH and many others.

**Comment by resucutie** [comment]
Could you give me an example on how I would use that? I'll include regardless if you give or not, but I was just curious about what it did

**Comment by resucutie** [comment]
either way, i forgor to close on commit

8510da5 closes this issue
