### ISSUE TITLE
typo on "good lock" section

### ISSUE THREAD

**Issue by Toastyisburning** [abUwUser/beyond-software-list#8]
**Which entry should be changed?**
Inform which entry has issues
> Good Lock

**What's wrong with?**
Provide a clear and cohesive description on what it lacks
> says "Samsumg" instead of "Samsung"

**What changes should be applied**
Provide what changes we need to make
> ➡️➡️➡️n⬅️⬅️⬅️

**Comment by resucutie** [comment]
Imma change  this if I remember to
